package com.jspider.spring_boot_simple_crud_with_mysql.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity representing an application user for JWT-based authentication.
 *
 * <p>The class is intentionally mapped to a physical table named {@code app_user}
 * to avoid the reserved-word collision with MySQL 8.x's {@code USER} keyword.
 * The {@link jakarta.persistence.Table @Table} annotation is therefore
 * mandatory and must not be removed (see AAP §0.1.4 / §0.7.5).</p>
 *
 * <p>The {@code password} column persists ONLY the BCrypt-hashed value;
 * plain-text passwords must never reach this entity. Hashing is performed
 * upstream in the {@code AuthService.register(...)} flow before
 * {@code UserRepository.save(...)} is invoked.</p>
 *
 * <p>The {@code role} column stores a single role identifier as a string
 * (e.g. {@code "USER"} or {@code "ADMIN"}). The {@code UserDetailsServiceImpl}
 * adapter is responsible for prefixing the value with {@code ROLE_} and
 * uppercasing it when building Spring Security's {@code SimpleGrantedAuthority}.
 * Keeping the role as a simple string here matches the AAP's single-field
 * design and avoids leaking Spring Security types into the entity layer.</p>
 */
@Entity
@Table(name = "app_user")
@Data
@NoArgsConstructor
@AllArgsConstructor
// Rule Applied
public class User {

    /**
     * Surrogate primary key generated by the database (MySQL {@code BIGINT
     * AUTO_INCREMENT}). Declared as {@link Long} (wrapper) — not {@code long}
     * primitive — so the value can be {@code null} for unsaved transient
     * instances created by {@code AuthService.register(...)}.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique login identifier. Database-level uniqueness is enforced via
     * {@code unique = true} so even if a higher-layer
     * {@code existsByUsername(...)} check is bypassed, duplicate inserts
     * still fail with a constraint violation.
     */
    @Column(unique = true, nullable = false)
    private String username;

    /**
     * BCrypt-hashed password. The entity layer makes no attempt to hash or
     * validate the value; the service layer is the sole owner of that
     * contract. Marked {@code nullable = false} to guarantee no row can
     * ever be persisted without a hash.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Single role token (e.g. {@code "USER"}, {@code "ADMIN"}). Required —
     * every authenticated principal must carry exactly one role string.
     */
    @Column(nullable = false)
    private String role;

}
