package com.jspider.spring_boot_simple_crud_with_mysql.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) that represents the JSON request body of
 * {@code POST /auth/login}.
 *
 * <p>The DTO is intentionally decoupled from the JPA {@code User} entity so
 * that the HTTP wire format never leaks the hashed password column and so that
 * Jackson can deserialise inbound JSON of the form
 * <pre>{ "username": "...", "password": "..." }</pre>
 * automatically using the public no-arg constructor generated by
 * {@link lombok.NoArgsConstructor} and the setters generated by
 * {@link lombok.Data}.</p>
 *
 * <p>The {@code password} field holds the RAW (plaintext) credential supplied
 * by the client. It is never persisted in this form &mdash; the configured
 * {@code DaoAuthenticationProvider} verifies it via
 * {@code BCryptPasswordEncoder.matches(rawPwd, hashedPwd)} against the BCrypt
 * hash stored in the {@code app_user.password} column. Callers MUST NOT log
 * this field, and downstream code MUST NOT call {@link #toString()} on this
 * object because Lombok's generated {@code toString()} includes every field by
 * default.</p>
 *
 * <p>There is intentionally NO {@code role} field on this DTO: the role is
 * read from the persisted {@code User} row after successful authentication and
 * is embedded into the issued JWT by {@code JwtUtil.generateToken(...)}.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
// Rule Applied
public class LoginRequestDto {

    /**
     * The username (login identifier) submitted by the client. Matches the
     * unique {@code username} column on the {@code User} entity / {@code
     * app_user} table.
     */
    private String username;

    /**
     * The RAW (plaintext) password submitted by the client. This value is
     * compared against the BCrypt hash stored in the database by
     * {@code DaoAuthenticationProvider} during
     * {@code AuthenticationManager.authenticate(...)}. It is NEVER persisted
     * in plaintext and MUST NOT be logged.
     */
    private String password;
}
