package com.jspider.spring_boot_simple_crud_with_mysql.dto;

import jakarta.validation.constraints.NotBlank;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) that represents the JSON request body of
 * {@code POST /auth/login}.
 *
 * <p>The DTO is intentionally decoupled from the JPA {@code User} entity so
 * that the HTTP wire format never leaks the hashed password column and so that
 * Jackson can deserialise inbound JSON of the form
 * <pre>{ "username": "...", "password": "..." }</pre>
 * automatically using the public no-arg constructor generated by
 * {@link lombok.NoArgsConstructor} and the setters generated by
 * {@link lombok.Data}.</p>
 *
 * <p><strong>Bean Validation (Jakarta Validation API):</strong> both string
 * fields are annotated with {@link NotBlank} so that null, empty, and
 * whitespace-only inputs are rejected by the {@code @Valid}-annotated
 * controller parameter BEFORE the request reaches
 * {@code AuthenticationManager.authenticate(...)}. Validation failures
 * surface as {@code MethodArgumentNotValidException} which
 * {@code GlobalExceptionHandler} maps to HTTP {@code 400 Bad Request} with a
 * descriptive envelope; this prevents the previously-observed pattern in
 * which malformed login bodies confusingly returned HTTP 401.</p>
 *
 * <p>The {@code password} field holds the RAW (plaintext) credential supplied
 * by the client. It is never persisted in this form &mdash; the configured
 * {@code DaoAuthenticationProvider} verifies it via
 * {@code BCryptPasswordEncoder.matches(rawPwd, hashedPwd)} against the BCrypt
 * hash stored in the {@code app_user.password} column. Callers MUST NOT log
 * this field, and downstream code MUST NOT call {@link #toString()} on this
 * object because Lombok's generated {@code toString()} includes every field by
 * default.</p>
 *
 * <p>There is intentionally NO {@code role} field on this DTO: the role is
 * read from the persisted {@code User} row after successful authentication and
 * is embedded into the issued JWT by {@code JwtUtil.generateToken(...)}.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
// Rule Applied
public class LoginRequestDto {

    /**
     * The username (login identifier) submitted by the client. Matches the
     * unique {@code username} column on the {@code User} entity / {@code
     * app_user} table.
     *
     * <p>{@link NotBlank} rejects {@code null}, empty, and whitespace-only
     * values at the controller boundary so that the request never reaches
     * {@code AuthenticationManager.authenticate(...)} with junk input. This
     * keeps the {@code 401 Unauthorized} response semantic precise: 401 is
     * reserved for genuine credential mismatches (anti-enumeration safe),
     * while {@code 400 Bad Request} is returned for malformed payloads.</p>
     */
    @NotBlank(message = "username must not be blank")
    private String username;

    /**
     * The RAW (plaintext) password submitted by the client. This value is
     * compared against the BCrypt hash stored in the database by
     * {@code DaoAuthenticationProvider} during
     * {@code AuthenticationManager.authenticate(...)}. It is NEVER persisted
     * in plaintext and MUST NOT be logged.
     *
     * <p>{@link NotBlank} rejects {@code null}, empty, and whitespace-only
     * values at the controller boundary.</p>
     */
    @NotBlank(message = "password must not be blank")
    private String password;
}
