package com.jspider.spring_boot_simple_crud_with_mysql.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) that represents the JSON request body of
 * {@code POST /auth/register}.
 *
 * <p>The DTO is intentionally decoupled from the JPA {@code User} entity so that
 * the HTTP wire format never leaks the BCrypt-hashed {@code password} column nor
 * the auto-generated {@code id} primary key. Jackson deserialises inbound JSON of
 * the form
 * <pre>{ "username": "...", "password": "...", "role": "..." }</pre>
 * using the public no-arg constructor generated by Lombok's
 * {@link NoArgsConstructor} and the setters generated by Lombok's {@link Data}.</p>
 *
 * <h2>Bean Validation (QA CP2 Issues #2, #3, #4, #5)</h2>
 *
 * <p>Every field carries Jakarta Bean Validation constraints so that the controller
 * can reject malformed registration payloads with a clean HTTP {@code 400 Bad
 * Request} (via {@code GlobalExceptionHandler}'s
 * {@code MethodArgumentNotValidException} handler) BEFORE the request ever reaches
 * the service layer or the database:</p>
 * <ul>
 *   <li><b>{@code username}</b> — {@code @NotBlank} rejects {@code null}, empty
 *       string, and whitespace-only values (closes CP2 issue #2 — previously a
 *       zero-length username was happily persisted with HTTP 201).
 *       {@code @Size(min=3, max=50)} enforces a 3-50 character business range
 *       which is comfortably narrower than the underlying
 *       {@code app_user.username VARCHAR(255)} column, so the application
 *       returns a clean 400 long before MySQL's data-truncation logic produces
 *       the {@code DataIntegrityViolationException} that previously surfaced as
 *       HTTP 500 (closes CP2 issue #5).</li>
 *   <li><b>{@code password}</b> — {@code @NotBlank} closes the empty-password
 *       authentication-bypass attack described in CP2 issue #3, where the
 *       endpoint accepted an empty string and BCrypt happily hashed it,
 *       producing a stored credential that the corresponding empty-password
 *       login attempt would match.
 *       {@code @Size(min=8, max=100)} establishes an industry-standard minimum
 *       password length while still letting BCrypt accept any reasonable
 *       password (BCrypt itself silently truncates at 72 bytes, hence the
 *       upper bound at 100 to surface obviously-wrong inputs cleanly).</li>
 *   <li><b>{@code role}</b> — {@code @NotBlank} closes CP2 issue #4 where a
 *       missing {@code role} field flowed all the way to JPA / MySQL and
 *       surfaced as a {@code DataIntegrityViolationException} mapped to HTTP
 *       500 (because the column is declared {@code @Column(nullable=false)}
 *       on the {@code User} entity). With the validation in place, the
 *       request is rejected with HTTP 400 before the DB is touched.
 *       {@code @Size(max=20)} matches the practical ceiling of role names
 *       like {@code "USER"} or {@code "ADMIN"} stored without the
 *       {@code ROLE_} prefix (see {@code UserDetailsServiceImpl}).</li>
 * </ul>
 *
 * <p>The annotations above only take effect when the controller method that
 * receives this DTO declares {@code @Valid} on the {@code @RequestBody}
 * parameter (see {@code AuthController#register(RegisterRequestDto)}) AND the
 * {@code spring-boot-starter-validation} dependency is on the classpath
 * (added to {@code pom.xml} as part of this CP2 remediation).</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
// Rule Applied
public class RegisterRequestDto {

    /**
     * Desired login identifier for the new application user.
     *
     * <p>{@code @NotBlank} rejects {@code null}, empty string, and
     * whitespace-only values. {@code @Size(min=3, max=50)} enforces a
     * sensible business-range and prevents MySQL's
     * {@code VARCHAR(255)} truncation on oversized inputs (CP2 issues
     * #2 and #5).</p>
     */
    @NotBlank(message = "username must not be blank")
    @Size(min = 3, max = 50, message = "username must be between 3 and 50 characters")
    private String username;

    /**
     * Raw (plaintext) password the caller wishes to set on the new user;
     * BCrypt-hashed by {@code AuthService.register(...)} via
     * {@code PasswordEncoder.encode(...)} before it touches the
     * {@code app_user.password} column.
     *
     * <p>{@code @NotBlank} guards against the empty-string credential
     * that would otherwise be hashed and stored (CP2 issue #3 — the
     * subsequent empty-password login would succeed and grant a JWT,
     * an effective authentication bypass).
     * {@code @Size(min=8, max=100)} establishes a minimum-strength floor
     * and an upper bound aligned with BCrypt's documented 72-byte
     * working limit.</p>
     */
    @NotBlank(message = "password must not be blank")
    @Size(min = 8, max = 100, message = "password must be between 8 and 100 characters")
    private String password;

    /**
     * Single role identifier (e.g. {@code "USER"} or {@code "ADMIN"})
     * persisted into the {@code app_user.role} column verbatim. The
     * {@code ROLE_} prefix Spring Security expects is added at runtime
     * by {@code UserDetailsServiceImpl#loadUserByUsername(...)} and
     * never stored in the database (see CP2 evidence: bob_cp2 stored as
     * {@code 'ADMIN'} but emitted in JWT as {@code 'ROLE_ADMIN'}).
     *
     * <p>{@code @NotBlank} closes CP2 issue #4 — a missing role field
     * was previously sent through to JPA and surfaced as a
     * {@code DataIntegrityViolationException} on the
     * {@code @Column(nullable=false)} constraint, returning HTTP 500.</p>
     */
    @NotBlank(message = "role must not be blank")
    @Size(max = 20, message = "role must be at most 20 characters")
    private String role;
}
