package com.jspider.spring_boot_simple_crud_with_mysql.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) that represents the JSON request body of
 * {@code POST /auth/register}.
 *
 * <p>The DTO is intentionally decoupled from the JPA {@code User} entity so that
 * the HTTP wire format never leaks the BCrypt-hashed {@code password} column nor
 * the auto-generated {@code id} primary key. Jackson deserialises inbound JSON of
 * the form
 * <pre>{ "username": "...", "password": "...", "role": "..." }</pre>
 * using the public no-arg constructor generated by Lombok's
 * {@link NoArgsConstructor} and the setters generated by Lombok's {@link Data}.</p>
 *
 * <p>Service-layer protections in {@code AuthService.register(...)} guard
 * against duplicate usernames via
 * {@code UserRepository.existsByUsername(...)}; that check throws an
 * {@code IllegalArgumentException} (mapped to a generic 4xx/5xx response by
 * Spring's default error handling) if the supplied username is already taken.
 * BCrypt password hashing is applied unconditionally to whatever password
 * value is submitted, and the persisted user's role is stored verbatim
 * (with the {@code ROLE_} prefix added at runtime by
 * {@code UserDetailsServiceImpl#loadUserByUsername(...)}, never in the
 * database).</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
// Rule Applied
public class RegisterRequestDto {

    /**
     * Desired login identifier for the new application user. Persisted into
     * the unique {@code app_user.username} column on the {@code User} entity
     * after {@code AuthService.register(...)}'s duplicate-username guard
     * (via {@code UserRepository.existsByUsername(...)}) confirms the value
     * is not already taken.
     */
    private String username;

    /**
     * Raw (plaintext) password the caller wishes to set on the new user;
     * BCrypt-hashed by {@code AuthService.register(...)} via
     * {@code PasswordEncoder.encode(...)} before it touches the
     * {@code app_user.password} column. Never persisted in plaintext and
     * never echoed in any log line.
     */
    private String password;

    /**
     * Single role identifier (e.g. {@code "USER"} or {@code "ADMIN"})
     * persisted into the {@code app_user.role} column verbatim. The
     * {@code ROLE_} prefix Spring Security expects is added at runtime
     * by {@code UserDetailsServiceImpl#loadUserByUsername(...)} and
     * never stored in the database.
     */
    private String role;
}
