package com.jspider.spring_boot_simple_crud_with_mysql.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) that represents the JSON request body of
 * {@code POST /auth/register}.
 *
 * <p>The DTO is intentionally decoupled from the JPA {@code User} entity so that
 * the HTTP wire format never leaks the BCrypt-hashed {@code password} column nor
 * the auto-generated {@code id} primary key. Jackson deserialises inbound JSON of
 * the form
 * <pre>{ "username": "...", "password": "...", "role": "..." }</pre>
 * using the public no-arg constructor generated by Lombok's
 * {@link NoArgsConstructor} and the setters generated by Lombok's {@link Data}.</p>
 *
 * <p><strong>Bean Validation (Jakarta Validation API):</strong> all three string
 * fields are annotated with {@link NotBlank} so that null, empty, and
 * whitespace-only inputs are rejected by the {@code @Valid}-annotated
 * controller parameter BEFORE any service-layer logic runs. The
 * {@code username} additionally carries a {@link Size} upper bound that mirrors
 * the {@code VARCHAR(255)} column width of {@code app_user.username} — this
 * pre-empts the {@code Data truncation: Data too long for column 'username'}
 * {@code DataIntegrityViolationException} that MySQL would otherwise raise at
 * insert time. Validation failures bubble up as
 * {@code MethodArgumentNotValidException} which is mapped to HTTP {@code 400
 * Bad Request} by {@code GlobalExceptionHandler}.</p>
 *
 * <p>Service-layer protections in {@code AuthService.register(...)} guard
 * against duplicate usernames via
 * {@code UserRepository.existsByUsername(...)}; that check throws an
 * {@code IllegalArgumentException} which is mapped to HTTP {@code 400 Bad
 * Request} by {@code GlobalExceptionHandler}. BCrypt password hashing is
 * applied unconditionally to whatever password value is submitted, and the
 * persisted user's role is stored verbatim (with the {@code ROLE_} prefix
 * added at runtime by
 * {@code UserDetailsServiceImpl#loadUserByUsername(...)}, never in the
 * database).</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
// Rule Applied
public class RegisterRequestDto {

    /**
     * Desired login identifier for the new application user. Persisted into
     * the unique {@code app_user.username} column on the {@code User} entity
     * after {@code AuthService.register(...)}'s duplicate-username guard
     * (via {@code UserRepository.existsByUsername(...)}) confirms the value
     * is not already taken.
     *
     * <p>{@link NotBlank} rejects {@code null}, empty (zero-length), and
     * whitespace-only values at the controller boundary. {@link Size} caps
     * the length at 255 characters to match the {@code VARCHAR(255)} column
     * width of {@code app_user.username} and prevent MySQL truncation
     * errors at insert time.</p>
     */
    @NotBlank(message = "username must not be blank")
    @Size(max = 255, message = "username must be at most 255 characters")
    private String username;

    /**
     * Raw (plaintext) password the caller wishes to set on the new user;
     * BCrypt-hashed by {@code AuthService.register(...)} via
     * {@code PasswordEncoder.encode(...)} before it touches the
     * {@code app_user.password} column. Never persisted in plaintext and
     * never echoed in any log line.
     *
     * <p>{@link NotBlank} rejects {@code null}, empty, and whitespace-only
     * values so that the registration request cannot create a row with an
     * effectively-unusable password hash.</p>
     */
    @NotBlank(message = "password must not be blank")
    private String password;

    /**
     * Single role identifier (e.g. {@code "USER"} or {@code "ADMIN"})
     * persisted into the {@code app_user.role} column verbatim. The
     * {@code ROLE_} prefix Spring Security expects is added at runtime
     * by {@code UserDetailsServiceImpl#loadUserByUsername(...)} and
     * never stored in the database.
     *
     * <p>{@link NotBlank} rejects {@code null}, empty, and whitespace-only
     * values; this pre-empts the {@code PropertyValueException: not-null
     * property references a null or transient value: User.role} that
     * Hibernate would otherwise raise on save.</p>
     */
    @NotBlank(message = "role must not be blank")
    private String role;
}
